### PR TITLE
implemented LoadFromResourceName and LoadFromStream methods

### PR DESCRIPTION
**Pull request by daar**
Hi!
I have implemented two new methods that make it more easy for me to use SynFacilSyn in my application. The LoadFromStream method is the base and LoadFromFile and LoadFromResourceName are using that method.
Hope you can push it to the master.
Regards, daar.

### CODE REVIEW

**Comment by t-edson** [comment]
Ok. Let me check first the changes and if no problem, it will be pulled.

**Comment by daar** [comment]
Thanks!

**Comment by t-edson** [comment]
@daar, I have detected some problem after the new changes. 
Check the project sample: /Speed_Test_Project
The code raises an exception when triying: memo3.Lines.LoadFromFile('Prueba.xml'), after hlt1.LoadFromFile('Prueba.xml');

**Comment by t-edson** [comment]
I have modified LoadFromFile: (added "fs.Free;"):

```
procedure TSynFacilSyn.LoadFromFile(const Filename: string);
var
  fs: TFileStream;
begin
  try
    fs := TFileStream.Create(Filename, fmOpenRead);
    fs.Position := 0;
    LoadFromStream(fs);
    fs.Free;     //added
  except
    on e: Exception do begin
      //completa el mensaje
      e.Message:=ERROR_LOADING_ + Filename + #13#10 + e.Message;
      fs.Free;
      raise   //genera de nuevo
    end;
  end;
end;
```
It works now.

**Pull request merged**
